project:
  type: website
  output-dir: docs

website:
  title: "Jacob Coggshall"
  navbar:
   background: primary
   left:
     - href: index.qmd
       text: Home
     - about.qmd
     
     - prospects.qmd

format:
  html:
    theme: quartz
    css: styles.css

editor: visual

